import mock
setwarnings = mock.Mock()
setmode     = mock.Mock()
BOARD       = mock.Mock()
cleanup     = mock.Mock()
setup       = mock.Mock()
OUT         = mock.Mock()
output      = mock.Mock()
IN          = mock.Mock()
input       = mock.Mock()
